onlyBuiltDependencies:
  - '@firebase/util'
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - core-js
  - esbuild
  - esbuild
  - oniguruma
  - protobufjs
  - sharp
  - unrs-resolver
